# Generated by Django 3.1.3 on 2020-11-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/api/images')),
                ('Size', models.IntegerField()),
                ('Units', models.CharField(choices=[('marla', 'MARLA'), ('square_feet', 'SQUARE_FEET'), ('square_yards', 'SQUARE_YARDS')], default='MARLA', max_length=128)),
                ('Beds', models.IntegerField()),
                ('Baths', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(choices=[('property', 'PROPERTY'), ('land', 'LAND'), ('commercial', 'COMMERCIAL')], default='PROPERTY', max_length=128)),
                ('Construction_status', models.CharField(choices=[('complete', 'COMPLETE'), ('under_construction', 'UNDER_CONSTRUCTION')], default='COMPLETE', max_length=128)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
