# Generated by Django 3.1.3 on 2020-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='City',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='Location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Image',
            field=models.ImageField(blank=True, default='media/api/images/house.png', null=True, upload_to='media/api/images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Type',
            field=models.CharField(choices=[('property', 'PROPERTY'), ('plot', 'PLOT'), ('commercial', 'COMMERCIAL')], default='PROPERTY', max_length=128),
        ),
    ]
