# Generated by Django 3.1.3 on 2020-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201202_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Purpose',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
