# Generated by Django 3.1.3 on 2020-12-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201204_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
