# Generated by Django 3.1.3 on 2020-12-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Units',
            field=models.CharField(choices=[('marla', 'MARLA'), ('kanal', 'KANAL'), ('square_meters', 'SQUARE_METERS'), ('square_yards', 'SQUARE_YARDS')], default='MARLA', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
