# Generated by Django 3.1.3 on 2020-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201216_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
