# Generated by Django 3.1.3 on 2020-12-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201220_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Features',
            new_name='Featured',
        ),
    ]
