# Generated by Django 3.1.3 on 2020-12-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/api/images')),
                ('Ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ad')),
            ],
        ),
    ]
