# Generated by Django 3.1.3 on 2020-12-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_adimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/api/images'),
        ),
        migrations.AddField(
            model_name='ad',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/api/images'),
        ),
        migrations.AddField(
            model_name='ad',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/api/images'),
        ),
        migrations.AddField(
            model_name='ad',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/api/images'),
        ),
        migrations.AddField(
            model_name='ad',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/api/images'),
        ),
        migrations.DeleteModel(
            name='AdImages',
        ),
    ]
