# Generated by Django 3.1.3 on 2020-12-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201222_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='Title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
