# Generated by Django 3.1.3 on 2020-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_saved_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
