# Generated by Django 3.1.3 on 2020-12-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_saved_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='Image',
            field=models.ImageField(blank=True, default='media/api/images/house.png', null=True, upload_to='media/api/images'),
        ),
    ]
