# Generated by Django 3.1.3 on 2020-12-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_saved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Additional_specifications',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ItemAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField(null=True)),
                ('Price', models.IntegerField()),
                ('Discounted_Price', models.IntegerField(null=True)),
                ('Category', models.CharField(choices=[('electric', 'ELECTRIC'), ('paints', 'PAINTS'), ('wallpapers', 'WALLPAPERS'), ('construction_tools', 'CONSTRUCTION_TOOLS'), ('building_material', 'BUILDING_MATERIAL'), ('bathroom', 'BATHROOM'), ('lighting', 'LIGHTING'), ('hardware', 'HARDWARE'), ('decor', 'DECOR'), ('security', 'SECURITY'), ('kitchen', 'KITCHEN'), ('walls_and_flooring', 'WALLS_AND_FLOORING')], default='construction_tools', max_length=128)),
                ('Type', models.CharField(max_length=128)),
                ('Additional_specifications', models.CharField(max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
