# Generated by Django 3.1.3 on 2020-12-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201225_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemad',
            name='Image',
            field=models.ImageField(blank=True, default='media/api/images/tools.png', null=True, upload_to='media/api/images'),
        ),
    ]
