# Generated by Django 3.1.3 on 2021-02-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_itemad_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
