# Generated by Django 3.1.3 on 2021-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cell_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
