# Generated by Django 3.1.3 on 2021-03-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210302_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='Image1',
            field=models.ImageField(blank=True, default='media/api/images/random.png', null=True, upload_to='media/api/images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Image2',
            field=models.ImageField(blank=True, default='media/api/images/random.png', null=True, upload_to='media/api/images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Image3',
            field=models.ImageField(blank=True, default='media/api/images/random.png', null=True, upload_to='media/api/images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Image4',
            field=models.ImageField(blank=True, default='media/api/images/random.png', null=True, upload_to='media/api/images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='Image5',
            field=models.ImageField(blank=True, default='media/api/images/random.png', null=True, upload_to='media/api/images'),
        ),
    ]
