# Generated by Django 3.1.3 on 2021-03-07 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_auto_20210305_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('taxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Qty', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Image', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('Brand', models.CharField(blank=True, max_length=200, null=True)),
                ('Category', models.CharField(choices=[('electric', 'ELECTRIC'), ('paints', 'PAINTS'), ('wallpapers', 'WALLPAPERS'), ('construction_tools', 'CONSTRUCTION_TOOLS'), ('building_material', 'BUILDING_MATERIAL'), ('bathroom', 'BATHROOM'), ('lighting', 'LIGHTING'), ('hardware', 'HARDWARE'), ('decor', 'DECOR'), ('security', 'SECURITY'), ('kitchen', 'KITCHEN'), ('walls_and_flooring', 'WALLS_AND_FLOORING')], default='ELECTRIC', max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('NumReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('InStock', models.BooleanField(blank=True, default=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Rating', models.IntegerField(blank=True, default=0, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('ShippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='Type',
            field=models.CharField(choices=[('property', 'PROPERTY'), ('plot', 'PLOT'), ('commercial', 'COMMERCIAL'), ('flat', 'FLAT'), ('penthouse', 'PENTHOUSE')], default='PROPERTY', max_length=128),
        ),
        migrations.DeleteModel(
            name='ItemAD',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
