# Generated by Django 3.1.3 on 2021-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210307_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='InStock',
        ),
        migrations.AddField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
