# Generated by Django 3.1.3 on 2021-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210307_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=128)),
                ('Price_to_income', models.FloatField(blank=True, null=True)),
                ('Mortgage_interest_ratio', models.FloatField(blank=True, null=True)),
                ('Price_to_rent', models.FloatField(blank=True, null=True)),
                ('rental_yield', models.FloatField(blank=True, null=True)),
                ('Price_per_sqr_mtr', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
