# Generated by Django 3.1.3 on 2021-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_priceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Title_image', models.ImageField(blank=True, default=None, null=True, upload_to='media/api/images')),
                ('content', models.TextField()),
                ('extra_image1', models.ImageField(blank=True, default=None, null=True, upload_to='media/api/images')),
                ('extra_image2', models.ImageField(blank=True, default=None, null=True, upload_to='media/api/images')),
                ('extra_image3', models.ImageField(blank=True, default=None, null=True, upload_to='media/api/images')),
            ],
        ),
    ]
