# Generated by Django 3.1.3 on 2021-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='genre',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
