# Generated by Django 3.1.3 on 2021-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_blog_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyIndices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=128)),
                ('y_2010', models.FloatField(blank=True, null=True)),
                ('y_2011', models.FloatField(blank=True, null=True)),
                ('y_2012', models.FloatField(blank=True, null=True)),
                ('y_2013', models.FloatField(blank=True, null=True)),
                ('y_2014', models.FloatField(blank=True, null=True)),
                ('y_2015', models.FloatField(blank=True, null=True)),
                ('y_2016', models.FloatField(blank=True, null=True)),
                ('y_2017', models.FloatField(blank=True, null=True)),
                ('y_2018', models.FloatField(blank=True, null=True)),
                ('y_2019', models.FloatField(blank=True, null=True)),
                ('y_2020', models.FloatField(blank=True, null=True)),
                ('y_2021', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
