# Generated by Django 3.1.3 on 2021-03-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_yearlyindices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyindices',
            name='y_2010',
        ),
        migrations.RemoveField(
            model_name='yearlyindices',
            name='y_2011',
        ),
        migrations.RemoveField(
            model_name='yearlyindices',
            name='y_2012',
        ),
    ]
