# Generated by Django 3.1.3 on 2021-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210413_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='NumReviews',
        ),
    ]
