# Generated by Django 3.1.3 on 2021-04-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_product_numreviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Rating',
        ),
    ]
