# Generated by Django 3.1.3 on 2021-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='PostalCode',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='ShippingPrice',
            new_name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
