# Generated by Django 3.1.1 on 2021-05-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
