# Generated by Django 3.1.1 on 2021-05-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
    ]
