# Generated by Django 3.1.1 on 2021-05-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='cell_no',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='email',
        ),
    ]
