# Generated by Django 3.1.1 on 2021-05-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210524_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='para0',
            field=models.TextField(blank=True, null=True),
        ),
    ]
