# Generated by Django 3.1.1 on 2021-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_blog_para0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
